mtconnect/cppagent

test/CMakeLists.txt

Integrated the Test Coverage Tool Gcov Lcov with the build system.
Run "make cov" to run tests and generate Report.

Test Coverage tool Gcov and Lcov Integration

---

unix/agent.conf

Upstart is employed by several major variants of Linux including Debian and Ubuntu as a convenient way of starting and stopping programs with system services. This simple startup script will start the MTConnect Agent with the PC.  This script is an alternative to the Unix daemonize startup script already provided with the MtConnect/cppagent.

Added Upstart Script for Debian based Linux Systems

---

agent/adapter.cpp
agent/data_item.hpp
samples/filter_example_1.3.xml
test/agent_test.cpp
test/agent_test.hpp
test/xml_parser_test.cpp
test/xml_parser_test.hpp
test/xml_printer_test.cpp
test/xml_printer_test.hpp

Filters of type period now work regardless of time settings (ignore timestamps, relative time) and follow the standard specification of seconds.
Since version 1.3 and earlier allowed filters to be specified as constraints, and the agent still supports this format, separate tests were created for 1.3 and current version.
Fixes #58.

Handle period filter in seconds and add tests

---

agent/component_event.cpp
samples/test_config.xml
test/agent_test.cpp
test/xml_printer_test.cpp

If initial value is specified, it will be used when a reset is triggered. If not, the value from the adapter is used.
Also, filters adjusted in test_config.xml as standard specifies "Either MINIMUM_DELTA or PERIOD can be defined, not both."
Fixes #59.

Use InitialValue when reset is triggered

---

README.md
agent/config.cpp
agent/xml_printer.cpp

I don't see a reason not to set 1.4 as the default.

Set default schema version to 1.4

---

agent/adapter.hpp
agent/agent.hpp
agent/config.hpp
agent/cutting_tool.hpp
test/connector_test.hpp

* Added the 'override' keyword to methods that should be overriding the behavior of a base class or implementing an abstract base class method
* This keyword allows the compiler the chance to spot when a virtual base class function has changed by the derived classes have not been updated

Use of C++ 11 'override' keyword

---

agent/adapter.cpp
agent/agent.cpp
agent/change_observer.cpp
agent/checkpoint.cpp
agent/component.cpp
agent/config.cpp
agent/globals.cpp
agent/options.cpp
agent/xml_printer.cpp
test/agent_test.cpp
test/change_observer_test.cpp
test/connector_test.cpp
test/globals_test.cpp

* Use of std::thread::sleep_for instead of dlib::sleep
* Replaced loops with C++11 ':' syntax

C++11 loops and threads

---

test/config_test.cpp

* Due to OS file caching the logger rollover mechanism does not obey the max size accurately

Bug Fix: Disabled failing test on Windows

---

README.md

PONG message format in README.md is invalid. `:` is not needed.

Fix PONG message format in README.

---

README.md
agent/adapter.cpp
agent/adapter.hpp
test/adapter_test.cpp
test/adapter_test.hpp

This pull request tries to overcome the limitation that values streamed from the adapter to the agent can not contain a pipe character on its own because the pipe is used as a protocol special character. See also issue #38.
For now only values and events are considered.

Added option to escape pipes in values of events and samples

---

.travis.yml

Add .travis.yml file for automated building to spot coding errors early. For a first step only release building on the newest Linux and OSX versions are checked. Later it can be extended with unit tests and so on.
What puzzles me is that for Linux c++11 is enabled. What are the compiler requirements for the master? I thought it is c++98 standard?
If the pull request is accepted, someone with admin rights on the cppagent repository must sign-in to [https://travis-ci.com](https://travis-ci.com/) and activate the build script. Then all further commits to master would be automatically checked and the success would be indicated in the commit log. (For example see https://github.com/lorenzhaas/cppagent/commits/master, red cross and green check mark.)
(Sorry for the mess with the first pull …

Add Travis CI build file

---

agent/service.cpp

`argc` holds the element count of `argv` and thus can't be negative (see also [cppreference](https://en.cppreference.com/w/cpp/language/main_function)). Even if OptionsList::parse() uses `while (aArgc > 0)` do not set `argc` to a negative number.

argc should be non-negative

---

agent/service.cpp

If one calls "agent config_file" the agent ignores the passed config file. Instead it tries to use agent.cfg of the current directory. If that also fails you see
Usage: agent  [<file>]
<file>               : The configuration file
on the command line... 😧
This commit passes the user defined config file to the normal procedure.

Let "agent config_file" be a shorthand for "agent run config_file"

---

agent/config.cpp
agent/service.cpp

Admittedly it's unlikely that one uses a single character for a device/config file. However, it strengthen the code and avoids undefined behavior.

Fix UB for short strings

---

agent/config.cpp

The missing endl is annoying because it makes parsing the agent version from cout complicated. Turns
Configuration search path: current directory and /Volumes/Foo/MTConnect Agent Version 1.4.0.12 - built on Sun Oct 20 17:39:45 2019
to
Configuration search path: current directory and /Volumes/Foo/
MTConnect Agent Version 1.4.0.12 - built on Sun Oct 20 17:39:45 2019

Add missing endl to debug message

---

README.md

I have set up multiple adapters based on the information in this readme, and multiple times I have gone down a long road of trying to understand why the Agent isn't receiving my pongs, only to discover its because I didn't provide a newline at the end. So I think it might be good to add this little note to that section so its more clear.

Added note about newlines in PING/PONG section

---

CMakeLists.txt
conanfile.py
src/agent.cpp
src/configuration/agent_config.cpp
test/agent_device_test.cpp
test/config_test.cpp
test/observation_test.cpp

Added `logging_level` as log configuration option. `level` also supported.

233 logging level not working

---

.github/workflows/build-docker-image.yml

I tried building the cross-platform image using this github workflow, but it failed after it reached the 6h limit.
So this file serves as a warning - it has a comment that it doesn't work. You can delete it if you'd prefer. 
I built the image today on an amd64 comp though - it took around 10 hours. It's the arm (sub-)image that takes so long - the amd part only takes 30mins or so. 
So I pushed the image up to our Docker hub for now - https://hub.docker.com/repository/docker/ladder99/agent

Workflow update

---

.github/workflows/build.yml
CMakeLists.txt
conanfile.py
test_package/CMakeLists.txt
test_package/config_test.cpp

Made option `development` for use with `conan build ...` command. This includes the `test_package` as part of the top level project useful for writing code and tests simultaneously. 
When `conan create` is used, the `test_package` is treated as a separate package the pulls in the `mtconnect_agent`.
This should make it easier to test and validate builds while still verifying the use of the mtconnect agent as an embedded library.

Begin integrating GitHub releases into workflow and integrated tests into build

---

.github/workflows/build-docker-image.yml
.github/workflows/build.yml
CMakeLists.txt
Dockerfile
README.md
agent/CMakeLists.txt
agent_lib/CMakeLists.txt
demo/agent/agent.mac

* Fixed the docker build and created a new option to generate the cpack zip file to another directory.
* `-o zip_destination=/home/agent` will create the zip file in the /home/agent directory. 
* This will also facilitate CD to distribute the zip files as part of the release.
* Development build now runs tests at the end of the `conan build`
* Changes to the cmake install
* Created dependency on cmake 3.26.4

Add deploy release cd workflow

---

Dockerfile

This address #314
The Docker image builds with and without build arguments. 
Tested with:
```
docker buildx build --tag mtconnect/agent:2.0.0.12_RC18 .
```
and
```
docker buildx build --build-arg UID=1200 --build-arg GID=1200 --tag mtconnect/agent:2.0.0.12_RC18 .
```

Add build args UID and GID

---

README.md

Updated README.md  file to reflect the change to the condition shdr format for the condition_id attribute.
`Conditions require six (6) fields as follows:
<timestamp>|<data_item_name>|<level>|<native_code>|<native_severity>|<qualifier>|<message>
for adapters providing conditionIds - the conditionId is added to the native_code field with a ':' delimiter.
<timestamp>|<data_item_name>|<level>|<native_code>|<condition_id:native_severity>|<qualifier>|<message>>`

Condition id shdr readme update

---

src/mtconnect/entity/json_printer.hpp
src/mtconnect/sink/mqtt_sink/mqtt_service.cpp
test_package/mqtt_sink_test.cpp

* Added state as a top level key for conditions:
For example:
```
{"Fault":{"value":"Temperature is too high","dataItemId":"ctmp","nativeCode":"X111","nativeSeverity":"BAD","qualifier":"HIGH","sequence":53,"timestamp":"2018-04-27T05:00:26.555666Z","type":"TEMPERATURE"}}
```

Fixed issue with publishing conditions without state

---

.github/workflows/build-docker-image.yml
CMakeLists.txt
README.md
src/mtconnect/configuration/agent_config.cpp
src/mtconnect/source/adapter/shdr/connector.cpp
src/mtconnect/source/adapter/shdr/connector.hpp
src/mtconnect/source/adapter/shdr/shdr_adapter.cpp
test_package/adapter_test.cpp
test_package/connector_test.cpp

* Use `Heartbeat = <hb>` as an override regardless of the value returned in `* PONG <hb>`

Added Heartbeat to the SHDR adapter to override

---

README.md
src/mtconnect/configuration/config_options.hpp
src/mtconnect/mqtt/mqtt_client.hpp
src/mtconnect/mqtt/mqtt_client_impl.hpp
src/mtconnect/mqtt/mqtt_server.hpp
src/mtconnect/mqtt/mqtt_server_impl.hpp
src/mtconnect/pipeline/json_mapper.cpp
src/mtconnect/sink/mqtt_sink/mqtt2_service.cpp
src/mtconnect/sink/mqtt_sink/mqtt2_service.hpp
test_package/json_mapping_test.cpp
test_package/mqtt_isolated_test.cpp

Added a simple last will capability to the agent. Will publish on the device topic for the agent device if available. 
`{AgentDeviceProbePath}/Availability}` with the value being `AVAILABLE` or `UNAVAILABLE`.

Mqtt last will and client id fix

---

.dockerignore

This folder is not necessary to copy to the Docker images.
This commit fixes #375.

chore: add `styles/old` to `.dockerignore`

---

src/mtconnect/pipeline/timestamp_extractor.hpp

boost log NAMED_SCOPE cannot be used because the boost log is set up differently in the sink DLL. ExtractTimestamp transform has an inline code that uses NAMED_SCOPE..
ld: Undefined symbols:
boost::log::v2_mt_posix::attributes::named_scope::push_scope(boost::log::v2_mt_posix::attributes::named_scope_entry const&), referenced from:
boost::log::v2_mt_posix::attributes::named_scope::sentry::sentry(boost::log::v2_mt_posix::basic_string_literal<char, std::__1::char_traits<char>> const&, boost::log::v2_mt_posix::basic_string_literal<char, std::__1::char_traits<char>> const&, unsigned int, boost::log::v2_mt_posix::attributes::named_scope_entry::scope_name_type) in

Resolve undefined boost::log symbol using ExtractTimestamp transform 

---

README.md

Your branch is up to date with 'origin/main-dev_readme_update'.
Changes to be committed:
modified:   README.md
* changed README.md version from 2.2 to 2.3
* Removed ⚠️Note:** Currently, there is no JSON parser functionality. Agent is expecting a raw SHDR-formatted string from MQTT Adapter/Source

 On branch main-dev_readme_update

---

demo/agent/agent.cfg
src/mtconnect/configuration/agent_config.cpp
src/mtconnect/sink/rest_sink/cached_file.hpp
src/mtconnect/sink/rest_sink/rest_service.cpp
test_package/agent_test.cpp
test_package/config_test.cpp
test_package/resources/styles/styles.xsl

Overwrites the syles sheet replacing the urn versions for mtconnect with the schema version configured in the agent.

Update schema version in stylesheets

---

src/mtconnect/agent.cpp
src/mtconnect/configuration/agent_config.cpp
src/mtconnect/configuration/config_options.hpp
src/mtconnect/printer/json_printer.cpp
src/mtconnect/printer/json_printer.hpp
src/mtconnect/printer/printer.hpp
src/mtconnect/printer/xml_printer.cpp
test_package/agent_test.cpp
test_package/config_test.cpp
test_package/json_printer_asset_test.cpp
test_package/json_printer_probe_test.cpp
test_package/json_printer_stream_test.cpp
test_package/xml_printer_test.cpp

Added `Sender = ...` configuration option. Sets value in the `<Header ...>` element of the docuemnts.

Added Sender configuration setting and tests closing #409

---

src/mtconnect/configuration/agent_config.cpp
test_package/agent_test.cpp

This PR should fix #420
AgentConfiguration::monitorThread message reports wrong number of seconds

Fix for issue 420

---

src/mtconnect/buffer/checkpoint.hpp
src/mtconnect/buffer/circular_buffer.hpp

#423 
Updated Checkpoint::updateDataItems() to remove orphans from observations map. Updated CircularBuffer::updateDataItems() to remove orphans from m_slidingBuffer

Issue-423: Crash when editing device dataitem in DeviceModel

---

CMakeLists.txt
src/mtconnect/source/adapter/shdr/shdr_adapter.cpp

* Fixed issue when preserve uuiid was false and device changed. Was not rebuilding pipeline.
* Version 2.3.0.6

419 UUID unavailable when changed

---

.github/workflows/build.yml

This addition should build and test the agent, and then generate a deb package for Ubuntu 22.04+.
Ubuntu 20.04 does not have the requisite libraries available to run this deb package if it is built in 22.04+, so we could create a different build action for that specific version if needed.

generic ubuntu deb package creation on release and add it to the release in github

---

CMakeLists.txt
conanfile.py
src/mtconnect/agent.cpp
src/mtconnect/device_model/data_item/data_item.cpp
src/mtconnect/device_model/data_item/data_item.hpp
src/mtconnect/mqtt/mqtt_client_impl.hpp
src/mtconnect/sink/mqtt_sink/mqtt2_service.cpp
src/mtconnect/sink/mqtt_sink/mqtt2_service.hpp
src/mtconnect/sink/rest_sink/rest_service.cpp
test_package/agent_test.cpp
test_package/mqtt_sink_2_test.cpp

* Assets in the mqtt2 sink now have MTConnectAssets header
* Fixed initial mqtt2 sample when inactive. Sample topic now populated with empty streams.
* Fixed pretty printing of assets in REST sink.

453 448 mqtt asset handling pretty printing

---

CMakeLists.txt
conanfile.py
src/mtconnect/mqtt/mqtt_client_impl.hpp
src/mtconnect/sink/mqtt_sink/mqtt_service.cpp
src/mtconnect/sink/mqtt_sink/mqtt_service.hpp
src/mtconnect/sink/rest_sink/rest_service.cpp
test_package/mqtt_sink_test.cpp

* Merged changes from main to main-dev.

Merge main to main dev

---

src/mtconnect/configuration/service.cpp

Path in windows is always unicode and needed to convert to string first.

There was a bug when a alternate config file was given to install

---

CMakeLists.txt
docker/alpine/Dockerfile
src/mtconnect/pipeline/json_mapper.cpp
src/mtconnect/pipeline/message_mapper.hpp
src/mtconnect/pipeline/topic_mapper.hpp

Fixed issues with MQTT adaper data item association.

associate source with adapter in json and topic mappers

---

src/mtconnect/pipeline/json_mapper.cpp
test_package/json_mapping_test.cpp

This change handles recovery when data items are not matched to consume additional data up to the next key.

Added error handling for json ingest

---

CMakeLists.txt
src/mtconnect/pipeline/shdr_token_mapper.cpp
test_package/data_item_mapping_test.cpp

Data sets used only support event categories. Samples can also have Data Set and Table representations as long as all the values are doubles.

Added support for sample data sets

---

CMakeLists.txt
src/mtconnect/device_model/data_item/unit_conversion.cpp
src/mtconnect/entity/xml_parser.cpp
test_package/unit_conversion_test.cpp

Handle conversions for things like kWh to Ws
Version 2.5.0.3

Support for unit conversions with multiple factors

---

.github/workflows/build.yml
CMakeLists.txt
src/mtconnect/pipeline/correct_timestamp.hpp

End of the transform did not pass on to next.

Fix transform to fix timestamps

---

src/mtconnect/pipeline/correct_timestamp.hpp
test_package/correct_timestamp_test.cpp

Fixed caching of timestamps when updated.

Fixed correct timestamp comparison

---

.github/workflows/build-docker-image.yml
CMakeLists.txt

* Switched docker build back to alpine
* Restarted buildx with arm64 and amd64 builds
It appears that QEMU has been fixed!

480 test alpine docker build on GitHub actions

---

src/mtconnect/entity/data_set.cpp
src/mtconnect/entity/data_set.hpp
src/mtconnect/entity/entity.cpp
src/mtconnect/entity/entity.hpp
src/mtconnect/entity/json_printer.hpp
src/mtconnect/entity/requirement.cpp
src/mtconnect/entity/xml_parser.cpp
src/mtconnect/entity/xml_printer.cpp
src/mtconnect/pipeline/json_mapper.cpp
src/mtconnect/pipeline/response_document.cpp
src/mtconnect/ruby/ruby_entity.hpp
test_package/correct_timestamp_test.cpp
test_package/data_item_mapping_test.cpp
test_package/embedded_ruby_test.cpp
test_package/entity_parser_test.cpp
test_package/json_mapping_test.cpp
test_package/response_document_test.cpp
test_package/table_test.cpp

* Made changes to support Visual Studio 2022 that no longer allowed data set recursive variants. 
* The new model explicitly creates a no-recusive TableRow and TableCell that can be part of a data set.

Visual studio 2022 porting issues

---

src/mtconnect/entity/data_set.hpp
test_package/table_test.cpp
test_package/test_utilities.hpp

* Fixed issues with streaming changes to data seet.

Fix data set issues

---

CMakeLists.txt
conanfile.py
src/mtconnect/entity/data_set.hpp

Refactored the implementation of the data set and table row to remove duplicate code.

Refactor data set

---

CMakeLists.txt
conan/mruby/conanfile.py
src/mtconnect/entity/data_set.hpp
src/mtconnect/printer/json_printer.cpp
src/mtconnect/source/adapter/adapter_pipeline.cpp
src/mtconnect/utilities.hpp
test_package/data_item_test.cpp
test_package/json_printer_stream_test.cpp

Fixed issues #555, #558, and #559:
* Fixed issue where camel casing of name with multiple _s caused crash.
* Fixed order in which validation occurs in the pipeline.
* Fixed json v1 issue with empty stream.

555 558 559 deprecated underscores and json v2 issues
