agent/adapter.hpp
agent/agent.cpp
agent/agent.hpp
agent/asset.hpp
agent/change_observer.hpp
agent/checkpoint.hpp
agent/component.hpp
agent/component_event.cpp
agent/component_event.hpp
agent/composition.hpp
agent/config.hpp
agent/connector.hpp
agent/cutting_tool.hpp
agent/data_item.hpp
agent/device.hpp
agent/globals.hpp
agent/options.hpp
agent/ref_counted.hpp
agent/rolling_file_logger.hpp
agent/service.hpp
agent/xml_parser.hpp
agent/xml_printer.hpp
test/agent_test.hpp
test/checkpoint_test.hpp
test/component_event_test.hpp
test/component_test.hpp
test/connector_test.hpp
test/data_item_test.hpp
test/test_globals.hpp
test/xml_printer_test.hpp

Tidied up header files
* Manually layout out method parameters
* Added 'const' where applicable to methods with implementations
* Removed 'a' prefix from function argument names
* Split 'Get' & 'Set' methods onto multiple lines so that a breakpoint can be added

Tidied up header files

---

agent/adapter.cpp
agent/agent.cpp
agent/agent.hpp
agent/checkpoint.cpp
agent/component.cpp
agent/component_event.cpp
agent/config.cpp
agent/connector.cpp
agent/cutting_tool.cpp
agent/data_item.cpp
agent/device.cpp
agent/globals.cpp
agent/service.cpp
agent/xml_parser.cpp
agent/xml_printer.cpp

* Used the 'auto' keyword where an explicit type was used for a variable declaration that was assigned a value based upon a function

Simple usage of 'auto' keyword in Agent source files

---

agent/adapter.cpp
agent/agent.cpp
agent/component_event.cpp
agent/config.cpp
agent/connector.cpp
agent/globals.cpp
agent/options.cpp
agent/rolling_file_logger.cpp
agent/service.cpp
agent/xml_parser.cpp
agent/xml_printer.cpp

* When using a character buffer it should be initialized to zero to prevent errors in subsequent string operations
* Pointers should be initialized to nullptr
* After deleting a heap pointer it should be set to nullptr to prevent duplicate deletion (it also aids debugging)

Buffer and Pointer initializations

---

agent/agent.cpp
agent/agent.hpp
agent/component_event.cpp
agent/connector.cpp
agent/connector.hpp
agent/rolling_file_logger.cpp
agent/rolling_file_logger.hpp

Replaced dlib::mutex & dlib::auto_mutex with std::mutex & std::lock_guard

Replaced dlib::mutex & dlib::auto_mutex with std equivalents

---

agent/change_observer.cpp
agent/change_observer.hpp
agent/checkpoint.cpp
agent/checkpoint.hpp
agent/component.cpp
agent/component.hpp
agent/component_event.cpp
agent/component_event.hpp
agent/config.hpp
agent/data_item.cpp
agent/data_item.hpp
agent/xml_parser.hpp
agent/xml_printer.cpp
agent/xml_printer.hpp
test/config_test.cpp

* Added 'const' directive to methods and parameters to avoid needless copying and state behaviour

const correctness changes

---

agent/CMakeLists.txt
agent/agent.cpp
agent/agent.hpp
agent/asset.hpp
agent/checkpoint.hpp
agent/component.cpp
agent/component.hpp
agent/component_event.cpp
agent/component_event.hpp
agent/cutting_tool.cpp
agent/data_item.cpp
agent/data_item.hpp
agent/device.cpp
agent/device.hpp
agent/xml_printer.cpp
test/checkpoint_test.cpp
test/component_event_test.cpp
test/component_test.cpp
test/data_item_test.cpp
test/device_test.cpp
test/xml_parser_test.cpp

* The [] operator is not read-only. This inserts a default item if it can't be found.
* Replaced the [] operator for read-only scenarios so that it can be used within 'const' functions

std::map is being used incorrectly

---

agent/xml_parser.cpp
agent/xml_parser.hpp

* Changed 'handleRefenence' to 'handleReference'

Fixed typo in method name

---

agent/config.cpp
test/xml_parser_test.cpp

* Uninitialized structures
* Unused variables

Static code analysis changes

---

lib/dlib/sockets/sockets_extensions.cpp
lib/dlib/sockets/sockets_kernel_2.cpp

Restored previous changes for IPV6 support on Linux (Windows not currently supported)

Restore IPV6 support

---

CMakeLists.txt
src/device_model/data_item.cpp
src/device_model/data_item.hpp
src/http_server/response.hpp
src/xml_parser.cpp

Fixed 1.7 compatibility issues.

Fixed coordinate system id, motion, and mutlipart

---

CMakeLists.txt
src/configuration/service.cpp

Fixed seg fault when no argument is passed to the agent. Displays usage from command line.

Added Windows no argument and no service

---

agent_lib/CMakeLists.txt
src/agent.cpp
src/asset/qif_document.cpp
src/asset/qif_document.hpp
src/asset/raw_material.cpp
src/asset/raw_material.hpp
src/configuration/agent_config.cpp
src/entity/entity.hpp
src/entity/factory.hpp
src/entity/requirement.cpp
src/entity/xml_parser.cpp
src/entity/xml_printer.cpp
src/pipeline/pipeline.hpp
src/pipeline/transform.hpp
src/sink/rest_sink/rest_service.cpp
src/sink/rest_sink/rest_service.hpp
src/sink/rest_sink/server.hpp
src/source/loopback_source.cpp
test/CMakeLists.txt
test/cutting_tool_test.cpp
test/json_printer_asset_test.cpp
test/qif_document_test.cpp
test/raw_material_test.cpp

Added parsers for QIF and RawMaterial.
Added support for multiple namespaces in raw nodes.

Parse qif and raw material assets

---

conanfile.py

* Small change because of issues on windows with doxygen dependencies

Default withdocs false

---

CMakeLists.txt
appveyor.yml
conanfile.py
src/mtconnect/configuration/agent_config.cpp
src/mtconnect/device_model/device.cpp
src/mtconnect/device_model/device.hpp
src/mtconnect/mqtt/mqtt_authorization.hpp
src/mtconnect/mqtt/mqtt_client.hpp
src/mtconnect/mqtt/mqtt_client_impl.hpp
src/mtconnect/mqtt/mqtt_server.hpp
src/mtconnect/mqtt/mqtt_server_impl.hpp
src/mtconnect/sink/rest_sink/rest_service.cpp
src/mtconnect/source/adapter/adapter.hpp
src/mtconnect/source/adapter/adapter_pipeline.hpp
src/mtconnect/source/adapter/agent_adapter/agent_adapter.hpp
src/mtconnect/source/adapter/agent_adapter/session.hpp
src/mtconnect/source/adapter/agent_adapter/session_impl.hpp
src/mtconnect/source/adapter/agent_adapter/url_parser.cpp
src/mtconnect/source/adapter/agent_adapter/url_parser.hpp
src/mtconnect/source/adapter/mqtt/mqtt_adapter.hpp
src/mtconnect/source/error_code.hpp
test/json_printer_stream_test.cpp
test/mqtt_isolated_test.cpp
test/relationship_test.cpp
tools/long_pull.rb

Merged development changes into master

---

agent_lib/CMakeLists.txt

Added atomic library to support ARM 32 Debian build.

Added atomic lib to agent_lib dependencies

---

.github/workflows/build.yml
conan/mruby/conanfile.py
conan/profiles/macos
conanfile.py
test_package/CMakeLists.txt
test_package/conanfile.py
test_package/embedded_ruby_test.cpp

Added trigger for pull request

Fix shared build for ci cd

---

.github/workflows/build.yml
test_package/CMakeLists.txt
test_package/conanfile.py

* Last step in fix for shared windows build

Fixed MSDEV shared build

---

Dockerfile

* Fixes build issues where it can't find aclocal

Added autoconf and automake to apt install

---

README.md

Review change to the README.md file to add the condition_id to the CONDITION SHDR format and example.   No code changes were made.

Main dev readme condition update

---

src/mtconnect/device_model/data_item/unit_conversion.cpp
test_package/unit_conversion_test.cpp

Added SQUARE_ support in the agent for square units.

Added square_ unit prefix conversions

---

src/mtconnect/configuration/agent_config.cpp
src/mtconnect/configuration/agent_config.hpp
test_package/config_test.cpp

* Adds support for json and xml configuration files.

Json configuration file

---

src/mtconnect/agent.hpp
src/mtconnect/configuration/agent_config.cpp
src/mtconnect/configuration/agent_config.hpp
src/mtconnect/observation/change_observer.cpp
src/mtconnect/observation/change_observer.hpp
src/mtconnect/observation/observation.cpp
src/mtconnect/observation/observation.hpp
src/mtconnect/pipeline/period_filter.hpp
src/mtconnect/pipeline/pipeline_contract.hpp
src/mtconnect/pipeline/shdr_token_mapper.cpp
src/mtconnect/utilities.hpp
test_package/agent_adapter_test.cpp
test_package/change_observer_test.cpp
test_package/checkpoint_test.cpp
test_package/config_test.cpp
test_package/data_item_mapping_test.cpp
test_package/duplicate_filter_test.cpp
test_package/embedded_ruby_test.cpp
test_package/mtconnect_xml_transform_test.cpp
test_package/period_filter_test.cpp
test_package/response_document_test.cpp
test_package/topic_mapping_test.cpp

First cut of 2.3 changes for condition id support.

Version 2.3 adding condition id to condition observation

---

CMakeLists.txt
src/mtconnect/configuration/agent_config.cpp
test_package/config_test.cpp

* Fixed setting AgentDeviceUUID in configuration

Fixed agent device uuid

---

README.md
src/mtconnect/configuration/agent_config.cpp
src/mtconnect/configuration/agent_config.hpp
src/mtconnect/configuration/config_options.hpp
src/mtconnect/observation/change_observer.cpp
src/mtconnect/observation/change_observer.hpp
src/mtconnect/pipeline/period_filter.hpp
src/mtconnect/sink/mqtt_sink/mqtt2_service.cpp
src/mtconnect/sink/mqtt_sink/mqtt_service.cpp
test_package/change_observer_test.cpp
test_package/config_test.cpp

* Fixed issue with legacy `DeviceTopic` changing to `ProbeTopic`

Added device topic as an alias for probe topic for mqtt sinks

---

.github/workflows/build-docker-image.yml
CMakeLists.txt
demo/Dockerfile
docker/alpine/Dockerfile
docker/replicator/Dockerfile
docker/ubuntu/Dockerfile
src/mtconnect/sink/rest_sink/file_cache.cpp
src/mtconnect/sink/rest_sink/file_cache.hpp
src/mtconnect/source/adapter/shdr/connector.hpp
test_package/adapter_test.cpp
test_package/mqtt_sink_test.cpp

* Cleaned up docker files per comments.

Cleaned up docker files and added minor version tag

---

CMakeLists.txt
conan/mruby/conanfile.py
conanfile.py
src/mtconnect/ruby/embedded.cpp
test_package/CMakeLists.txt
test_package/conanfile.py

* Added logging and improved load error handling for mruby scripts
* Addressed dll path issues on some platforms when building shared on windows.

Fixed dll copy on windows for shared on some build systems

---

src/mtconnect/pipeline/timestamp_extractor.hpp

Updated readme file to include format for the MQTT JSON ingress.

README.md MQTT JSON ingress protocol.

---

CMakeLists.txt
src/mtconnect/entity/xml_printer.cpp
test_package/agent_test.cpp

Removed `<...></...>` when property cdata is empty.

Empty cdata xml generation fix

---

README.md

Changes to be committed:
modified:   README.md
Added from V2.2 README.md file
* `AdapterIdentity` - Adapter Identity name used to prefix dataitems within the Agent device ids and names. 
*  #### MQTT Adapter/Source 
* ### MQTT JSON Ingress Protocol Version 2.0 Corrected minor spelling errors.

 On branch main-dev_readme_update

---

src/mtconnect/source/adapter/adapter_pipeline.hpp
src/mtconnect/source/adapter/shdr/shdr_adapter.cpp
test_package/agent_test.cpp

* fixed issue where the uuid changed

uuid command handling in agent not as expected

---

CMakeLists.txt
src/mtconnect/mqtt/mqtt_client_impl.hpp
src/mtconnect/source/adapter/mqtt/mqtt_adapter.cpp

Fixed port assignment issue in mqtt client.

Fixed port in url for MQTT service.

---

.github/workflows/build.yml
CMakeLists.txt
src/mtconnect/agent.cpp
src/mtconnect/device_model/data_item/data_item.cpp
src/mtconnect/device_model/data_item/data_item.hpp
test_package/agent_test.cpp
test_package/json_printer_probe_test.cpp

When a device becomes available, AVAILABILITY data item is AVAILABLE, all data items with initial values get set to the initial value.

Added initial value handling

---

demo/agent/agent.cfg
demo/agent/agent.dock
demo/agent/agent.mac
schemas/MTConnectStreams_2.3.xsd
schemas/MTConnectStreams_2.3_1.0.xsd

Updated schema version for demo agent cfg to 2.3.

updated the schema version for the demo to 2.3

---

CMakeLists.txt
src/mtconnect/configuration/agent_config.cpp

Fixed issue with UUID change in agent config adapters section.

Fixed UUID adapter config option

---

src/mtconnect/source/loopback_source.cpp

Added correct timestamps to loopback source
